<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Baize.Ecs</RootNamespace>
    <AssemblyName>Baize.Ecs</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\thirdparty\Friflo.Engine.ECS\Friflo.Engine.ECS.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\thirdparty\Friflo.Engine.ECS.Generator\Friflo.Engine.ECS.Generator.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
