<!-- SPDX-License-Identifier: MIT -->
<Project Sdk="Godot.NET.Sdk/4.8.0-dev">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Baize.GodotSlice</RootNamespace>
    <AssemblyName>godot-slice</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\modules\ecs\Baize.Ecs.csproj" />
    <ProjectReference Include="..\shooter-gameplay\Shooter.Gameplay.csproj" />
  </ItemGroup>
</Project>
