<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Shooter.Gameplay</RootNamespace>
    <AssemblyName>Shooter.Gameplay</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\libs\ecs\Sola3d.Ecs.csproj" />
    <ProjectReference Include="..\..\libs\ecs-generator\Sola3d.Ecs.Generator.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\thirdparty\Friflo.Engine.ECS.Generator\Friflo.Engine.ECS.Generator.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
