<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>GameObjectCoreTests</RootNamespace>
    <AssemblyName>gameobject-core-tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\modules\gameobject\Sola3d.GameObject.csproj" />
  </ItemGroup>
</Project>
